apiVersion: v1
kind: Service
metadata:
  name: cpe-backend
spec:

  ports:
  - protocol: "TCP"
    # Port of the service
    port: 8080
    # Port where tomcat is running
    targetPort: 8080
    # Port accessible from outside of cluster.
    nodePort: 30080
  # if you do not wish the backend endpoints accessible from outside of cluster, set it to ClusterIP instead
  type: NodePort
  #externalIPs:
  #- 172.17.0.2

  selector:
    app: cpe-backend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: cpe-backend   # no special char
  replicas: 2 # no. of pods to run
  template:
    metadata:
      labels:
        app: cpe-backend   # no special char
    spec:
      containers:
      - name: cpe-backend
        image: mockcpe:1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
