apiVersion: v1
kind: Service
metadata:
  name: cpe-backend
spec:

  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8080
    # Port to forward to inside the pod
    targetPort: 8080
    # Port accessible outside cluster
    #nodePort: 30002
  type: NodePort
  #externalIPs:
  #- 172.17.0.2

#  - protocol: TCP
#  port: 50605
#  nodePort: 8080
#  type: LoadBalancer

#  type: NodePort
#  ports:
#  - port: 8080
#    targetPort: 8080

  selector:
    app: cpe-backend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: cpe-backend   # no special char
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cpe-backend   # no special char
    spec:
      containers:
      - name: cpe-backend
        image: mockcpe
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
