apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
#  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:12.4
        name: postgres
        env:
          # Use secret in real usage
        - name: POSTGRES_PASSWORD
          value: test123
        ports:
        - containerPort: 5432
          name: postgres
        imagePullPolicy: Never
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /public/db-data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
