apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: postgres
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:12.4
        name: postgres
        env:
          # Use secret in real usage
        - name: POSTGRES_PASSWORD
          value: test123
        ports:
        - containerPort: 5432
          name: postgres
        # You may have to change to Never to avoid docker pull  
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: postgresvolmnt
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresvolmnt
        persistentVolumeClaim:
          # the name should match what is in db-pv.yml
          claimName: postgres-pv-claim
