# this is for creating a PersistentVolume and PersistentVolumeClaim to store the Postgres data
# TODO: 1. update the hostPath to the directory path where you want to persist the metadata
#       2. update the capacity.storage and requests.storage to the size you want
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    # update this to your own size
    storage: 11Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    # For local dev only. change this to your mount point
    path: "/public/db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # update this to your own size
      storage: 10Mi
