apiVersion: v1
kind: Service
metadata:
  name: frontend-client
spec:
  # This makes the app accessible outside of cluster (ie. from a browser)
  type: NodePort
  ports:
  - port: 80
  selector:
    app: frontend-client
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-client
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-client
    spec:
      containers:
      - name: frontend-client
        image: frontend-client:1.0.0
        ports:
        - containerPort: 80
        imagePullPolicy: Never
