apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-client   # no special char
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: frontend-client   # no special char
    spec:
      containers:
      - name: frontend-client
        image: frontend-client
        ports:
        - containerPort: 80
        imagePullPolicy: Never
